### ISSUE TITLE
Add All slides of 2019/08/17 COSCUP

### ISSUE THREAD

**Issue by sufuf3** [cloud-native-taiwan/meetups#12]
- [x] 10:00 ~ 10:40 和我一起用全裸容器網路改變世界 - https://speakerdeck.com/pichuang/20190817-container-bare-metal-for-networking
- [x] 10:45 ~ 11:15 我們與 M-CORD Release 的距離 - https://www.slideshare.net/aweimeow/mcord-release
- [x] ~11:20 ~ 12:00 SONA: A Telco Driven Cloud Native Network Management Solution~
- [ ] 12:05 ~ 12:30 Design principle and best practice of failpoint
- [x] 12:40 ~ 13:10 QUIC-GO: When HTTP/3 Meets Golang - https://slides.com/jalex-chang/http-3-leaks#/
- [x] 13:15 ~ 13:35 HA Prometheus solution - Thanos - https://docs.google.com/presentation/d/1KBs4FxYwFL6dsz_JUbPK4ZiKXYjsaLZI21VgVLI54I4/edit?usp=sharing
- [x] 13:40 ~ 14:10 Quick and Solid - Baremetal on OpenStack - http://bit.ly/32meoZ0
- [x] 14:15 ~ 14:30 Rancher Pipeline 使用經驗分享 - https://drive.google.com/file/d/1FyuAaI4BsNAVBr29lIf25BzbE2WqrZ-a/view
- [x] 14:30 ~ 14:50 Experience on gRPC rate limiting with Istio - https://speakerdeck.com/miyachen/experience-on-grpc-rate-limiting-with-istio
- [x] 14:55 ~ 15:25 Kubeflow 進行分散式深度學習訓練之作業排程瓶頸 #11
- [x] 15:30 ~ 16:00 Service Mesh and Observability around it - #13

**Comment by kairen** [comment]
#11 #13

**Comment by kkc** [comment]
https://docs.google.com/presentation/d/1KBs4FxYwFL6dsz_JUbPK4ZiKXYjsaLZI21VgVLI54I4/edit?usp=sharing HA Prometheus solution - Thanos

**Comment by sufuf3** [comment]
@kkc Thank you for sharing
