### ISSUE TITLE
Replace all redirect URL by its real URL.

### ISSUE THREAD

**Issue by hwchiu** [cloud-native-taiwan/meetups#26]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Redirect URL increases the complexity and difficulty to check daed link.

**What you expected to happen**:
I wish to use the awesome_bot to check all dead link but it only check the redirect status if the URL returns 301. which means if the redirect URL points to a 404 page, awesome_bot won't check the 404 status but only 301.

**How to reproduce it (as minimally and precisely as possible)**:
awesome_bot *.md

**Anything else we need to know?**:
Remove all redirect URL by its real URL and then we can add awssome_bot to travisci or circleci to check link status.

**Comment by pohsienshih** [comment]
#37
